### ISSUE TITLE
redesign?

### ISSUE THREAD

**Issue by ghost** [hezedu/px2vw#1]
![Без имени-1](https://user-images.githubusercontent.com/71665590/112069994-ea1eec00-8b7d-11eb-8cae-c2cbdce6ec33.png)
I was going to do the same thing, already drew the design, started the layout, and decided to check: is there any analogues on github? It turned out there are.

**Comment by hezedu** [comment]
This project is generally used on mobile, Very strange to use on the PC side

**Comment by ghost** [comment]
You just haven’t come across a layout for fullhd+ (2k, 4k) screens.

**Comment by hezedu** [comment]
OK, you guessed it right. I only have 1080p screen. 
It's looks useful.  I updated this project. 
- Added [English API documentation](https://github.com/hezedu/px2vw#apienglish), 
- Added `dist/` files. 
  You can direct <script> include:
  ```html
  <script src="https://cdn.jsdelivr.net/npm/px2vw@1.2.3/dist/px2vw.min.js"></script>
  ```
- The [online editor](https://hezedu.github.io/px2vw/) can be remember the configuration(width, minWidth).

**Comment by ghost** [comment]
One more thing: should we round up the number? To the thousandths after the dot. .toFixed(3) for example. The thing is that weak devices, especially phones, can freeze if they work with large numbers.

**Comment by hezedu** [comment]
For accuracy `toFixed` was remove in the previous version. 
The `px` seems to support [6 decimal places](https://jsbin.com/fiwedos/edit?html,output). `vw` should be wider.
Never heard of CSS can freeze with large numbers. Do you have relevant information? If it's true, I'll add it back.

**Comment by hezedu** [comment]
I just want to make a simple tool, and I don't have 4k screen. Redesign is unnecessary and difficult for me.
You can redesign by youself!
Give you a suggestion: Add minimum width option.

**Comment by ghost** [comment]
> For accuracy `toFixed` was remove in the previous version.
> Never heard of CSS can freeze with large numbers. Do you have relevant information? If it's true, I'll add it back.

If it was in the previous version, why did you remove it?

I had a Samsung galaxy A30 and the GSAP animation was freezing on it, but when I made it rounded (~~) the freezing disappeared. Freezing are possible when the processor of the device is too weak. On snapdragon 6xx+ processors you won't see that, but on a conditional Exynos 7904 it's quite possible

In any case, the higher the number, the higher the load. Would you agree that 20% is easier to calculate than 19.999999999999999997%?

> You can redesign by youself!

Are you suggesting I create a new branch or are you writing this so I just don't bother you anymore?

**Comment by hezedu** [comment]
Please provide the frozen value and the rounded value.

**Comment by hezedu** [comment]
20 is int. 
19.999999999999999997 is float. I think it is not easier to calculate than 19.9.
round is not same as toFixed. `vw` must have decimals.

**Comment by ghost** [comment]
> round is not same as toFixed. `vw` must have decimals.

![image](https://user-images.githubusercontent.com/71665590/112327729-bdc2b700-8cc6-11eb-902a-8a91e8abc20c.png)

**Comment by ghost** [comment]
> Please provide the frozen value and the rounded value.

I don't have this phone at the moment. I can't show it to you.

**Comment by hezedu** [comment]
At least show me the code that went wrong.

**Comment by ghost** [comment]
I can't show you. I don't have this code at the moment. Roughly speaking: moving blocks via transform and resizing via width and height caused small fps drops. When I did the rounding, freezing disappeared. Just take my word for it. You don't have to believe it.

**Comment by hezedu** [comment]
You can write a demo, Show how to round. 
`toFixed` or `Math.round`?
```js
var a = 19.79999999;
a.toFixed(3); 
// "19.800"
Math.round(a);
// 20
```

**Comment by ghost** [comment]
English is not my language, so I don't fully understand you. Are you asking what is the best way to round? It is better to round with Fix(3), because it is better to leave 3 characters after the point. 
`m = ((m / width) * 100).toFixed(3);`

But I have a feeling that's not what you mean.

**Comment by hezedu** [comment]
I can’t find any **CSS freeze** information. but I should be able to see **fps drops**.  Is there a demo about **fps drops**?

**Comment by ghost** [comment]
What is your device?

**Comment by hezedu** [comment]
win10 Chrome

**Comment by ghost** [comment]
To be honest, I don't really understand the point of the argument. I'm saying that on weak devices we may encounter small fps drops. This will be due to the fact that it is more difficult for a weak device to do the calculation. Plus, we have to store large numbers for some reason in a situation with a constant shortage of RAM. It feels like I'm trying to prove to you now that the Pentium 4 will freezing GTA 5. Fuck, well, it's clear enough. Let's do this: I admit defeat in an argument, you're right. I think it would be easier for both of us.

**Comment by hezedu** [comment]
For RAM, toFixed does have some performance improvements. 
I have updated to version 1.3.2: Added optional param [`fixedNum`](https://github.com/hezedu/px2vw#px2vwwidth-content-minwidth-fixednum).
