### ISSUE TITLE
Automatic deletion of lines that do not convert

### ISSUE THREAD

**Issue by accountnujen** [hezedu/px2vw#2]
Thanks for your project!
I would like to ask to add a fic: if there are no px values in the styles, those styles should be deleted. 

What I mean by that. 
For example here are the styles:
```
.file-wrap {
  width: 300px;
  border: 1px solid #bec4ce;
  border-radius: 10px;
  height: 90px;
  background: #eef5ff;
  position: relative;
  display: block;
  box-sizing: border-box;
  padding: 26px;
  cursor: pointer;
  transition: 0.25s all;
  user-select: none;
}
```

Of all the stuff here, I'll only need this:
```
.file-wrap {
  width: 300px;
  border: 1px solid #bec4ce;
  border-radius: 10px;
  height: 90px;
  padding: 26px;
}
```

At the moment, I have to manually delete unnecessary lines. It would be cool if it happened automatically!

**Comment by hezedu** [comment]
Sorry. This project just a simple conversion.
You can write two files, One file writes common style, one file only writes `px`.
___common.css___
```
.file-wrap {
  background: #eef5ff;
  position: relative;
  display: block;
  box-sizing: border-box;
  cursor: pointer;
  transition: 0.25s all;
  user-select: none;
}
```
___375_px.css___
```
.file-wrap {
  width: 300px;
  border: 1px solid #bec4ce;
  border-radius: 10px;
  height: 90px;
  padding: 26px;
}
```

**Comment by accountnujen** [comment]
I'm not talking about the script itself, but your site. Add this feature to the site, please.

**Comment by hezedu** [comment]
Site is demo of the script, will not provide features that the script does not have.
You can do it by youself.
